name: Auto Update Patrolling Sheet

on:
  schedule:
    - cron: "0 * * * *"   # हर 1 घंटे
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run automation
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: python update_sheet.py
